force-app/main/default/objects/H8_File_Upload_Configuration__mdt/H8_File_Upload_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to support with file upload configurations for the flow file upload component</description>
    <label>H8 File Upload Configuration</label>
    <pluralLabel>H8 File Upload Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_File_Upload_Configuration__mdt/fields/OverrideFileName__c.field-meta.xml
<CustomField>
    <fullName>OverrideFileName__c</fullName>
    <inlineHelpText>Enter a value that you want to change the uploaded file name to. I.e. you have handling Bank Statements you might want to change the name of the file to Bank Statement</inlineHelpText>
    <label>Override File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_File_Upload_Configuration__mdt/fields/ShareType__c.field-meta.xml
<CustomField>
    <fullName>ShareType__c</fullName>
    <description>The Visibility of the ContentDocumentLink to be created. Previously tied to ShareType but these are now separated out into Visibility and ShareType</description>
    <inlineHelpText>If using this flow for linking with an experience cloud you should select All Users</inlineHelpText>
    <label>Visibility</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AllUsers</fullName>
                <default>true</default>
                <label>AllUsers</label>
            </value>
            <value>
                <fullName>InternalUsers</fullName>
            </value>
            <value>
                <fullName>SharedUsers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_File_Upload_Configuration_Field__mdt/H8_File_Upload_Configuration_Field__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is a child to H8 File Upload Configuration and is where you can configure default values on the ContentVersion. As an example you may have a custom field that you want to store a set value in like File_Type__c = &apos;Bank Statement&apos;</description>
    <label>H8 File Upload Configuration Field</label>
    <pluralLabel>H8 File Upload Configuration Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_File_Upload_Configuration_Field__mdt/fields/Custom_Field__c.field-meta.xml
<CustomField>
    <fullName>Custom_Field__c</fullName>
    <inlineHelpText>Select the custom field that you want to set the value on</inlineHelpText>
    <label>Custom Field</label>
    <metadataRelationshipControllingField>H8_File_Upload_Configuration_Field__mdt.Content_Version_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>H8_File_Upload_Configuration_Fields</relationshipLabel>
    <relationshipName>H8_File_Upload_Configuration_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_File_Upload_Configuration_Field__mdt/fields/H8_File_Upload_Configuration__c.field-meta.xml
<CustomField>
    <fullName>H8_File_Upload_Configuration__c</fullName>
    <inlineHelpText>This is the configuration that the field is related to</inlineHelpText>
    <label>H8 File Upload Configuration</label>
    <referenceTo>H8_File_Upload_Configuration__mdt</referenceTo>
    <relationshipLabel>H8 File Upload Configuration Fields</relationshipLabel>
    <relationshipName>H8_File_Upload_Configuration_Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_File_Upload_Configuration_Field__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Enter the text value you want to store within the field</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/H8FlowFileUploadController.cls
/**
 * @description       : flow file upload controller
 *                      has to run without shared to support guest user access or temp permission issues
 * @author            : daniel@hyphen8.com
 * @last modified on  : 31/10/2024
 * @last modified by  : daniel@hyphen8.com
**/
public without sharing class H8FlowFileUploadController {

    private static H8_File_Upload_Configuration__mdt configurationRecord;
    public static H8_File_Upload_Configuration__mdt testConfigurationRecord;
    private static List<ContentVersion> contentVersions = new List<ContentVersion>();
    private static Set<Id> contentDocumentIdSet = new Set<Id>();

    /**
    * @description          method to update file data based on meta data configuration if available and for creation of content document links
    * @param                contentDocumentIds 
    * @param                configuration 
    * @param                recordId 
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled 
    public static void updateFileData(List<String> contentDocumentIds, String configuration, String recordId){
        getConfiguration(configuration);
        getContentDocumentIds(contentDocumentIds);
        if(null != recordId){    
            contentDocumentCreation(recordId);
        }

        if(null != configurationRecord){
            fileValuesSet();
        }
    }
    
    /**
    * @description          method to generate content document links
    * @param                recordId 
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private static void contentDocumentCreation(String recordId){
        List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
        for(Id contentDocumentId:contentDocumentIdSet){
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.ContentDocumentId = contentDocumentId;
            contentDocumentLink.LinkedEntityId = recordId;
            if(null != configurationRecord){
                contentDocumentLink.Visibility = configurationRecord.ShareType__c;
            }
            contentDocumentLinks.add(contentDocumentLink);
        }
        insert contentDocumentLinks;
    }

    /**
    * @description          method to set field values or rename file
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private static void fileValuesSet(){
        List<H8_File_Upload_Configuration_Field__mdt> childFieldUpdates = configurationRecord.H8_File_Upload_Configuration_Fields__r;
        if(childFieldUpdates.size() > 0){
            List<ContentVersion> contentVersionUpdates = new List<ContentVersion>();
            for(ContentVersion contentVersion:contentVersions){
                for(H8_File_Upload_Configuration_Field__mdt fieldUpdates:childFieldUpdates){
                    contentVersion.put(fieldUpdates.Custom_Field__r.QualifiedAPIName, fieldUpdates.Value__c);
                }
                if(null != configurationRecord.OverrideFileName__c){
                    contentVersion.Title = configurationRecord.OverrideFileName__c;
                }
                contentVersionUpdates.add(contentVersion);
            }
            update contentVersionUpdates;
        }
    }

    /**
    * @description                  method to process the content versions and get the relevant data
    * @param                        contentDocumentIds 
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    private static void getContentDocumentIds(List<String> contentDocumentIds){
        for(ContentVersion version:[SELECT Id, ContentDocumentId 
                                                FROM ContentVersion 
                                                WHERE ContentDocumentId IN:contentDocumentIds]){
            contentDocumentIdSet.add(version.ContentDocumentId);
            contentVersions.add(version);
        }
    }

    /**
    * @description                  method to pull in the metadata configuration
    * @param                        configuration 
    **/
    private static void getConfiguration(String configuration){
        try {
            configurationRecord = Test.isRunningTest() ? testConfigurationRecord : [SELECT Id, OverrideFileName__c, ShareType__c, 
                                                                                                (SELECT Id, Custom_Field__r.QualifiedAPIName, Value__c 
                                                                                                                FROM H8_File_Upload_Configuration_Fields__r) 
                                                                                                FROM H8_File_Upload_Configuration__mdt 
                                                                                                WHERE DeveloperName=:configuration 
                                                                                                LIMIT 1];
        } catch (Exception e){
            configurationRecord = new H8_File_Upload_Configuration__mdt();
        }
    }

    /**
    * @description                  aura method to delete a content document
    * @param                        contentVersionId 
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static void deleteContentDoc(String contentVersionId){
        try {
            ContentVersion contentVersion = [SELECT ContentDocumentId 
                                                        FROM ContentVersion 
                                                        WHERE Id=:contentVersionId 
                                                        LIMIT 1];
            ContentDocument contentDocument = new ContentDocument(Id=contentVersion.ContentDocumentId);
            delete contentDocument;
        } catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description              aura method to get existing files
    * @param                    contentDocumentIds
    * @return                   List<objFiles> 
    **/
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static String getExistingFiles(List<String> contentDocumentIds){
        List<ContentVersion> contentVersions = [SELECT Id, ContentModifiedDate, ContentSize, ContentDocumentId, ContentDocument.FileExtension, ContentDocument.Title FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentIds AND IsLatest = TRUE];
        return generateExistingFilesResponse(contentVersions);
    }

    /**
    * @description              method to generate our json for returning to the front end
    * @param                    contentVersions 
    * @return                   String 
    **/
    private static String generateExistingFilesResponse(List<ContentVersion> contentVersions){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeFieldName('files');
        gen.writeStartArray();
        for(ContentVersion version:contentVersions){
            gen.writeStartObject();
                gen.writeStringField('name', version.ContentDocument.Title);
                gen.writeStringField('documentId', version.ContentDocumentId);
                gen.writeStringField('contentVersionId', version.Id);
                gen.writeStringField('fileExtension', version.ContentDocument.FileExtension);
                gen.writeStringField('contentDescription', getContentDescription(version));
            gen.writeEndObject();
        }
        gen.writeEndArray();
        gen.writeEndObject();
        return gen.getAsString();
    }

    /**
    * @description              method to get the content description for returning with the contentversion information
    * @param                    contentVersion 
    * @return                   String 
    **/
    private static String getContentDescription(ContentVersion contentVersion){
        Integer kbSize = contentVersion.ContentSize / 1000;
        return contentVersion.ContentModifiedDate + ' - ' + kbSize + 'KB - ' + contentVersion.ContentDocument.FileExtension; 
    }

}