force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <inlineHelpText>This is the API Name for the flow that you want to render</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <inlineHelpText>Use SLDS Icons here with the format standard:opportunity</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is the order that the section should appear in</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you tick this box you can set the name of section as a custom label - you do not need to include $Label. just the Label API Name will be enough</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/H8FlowFormControllerTest.cls
/**
 * @description       : H8FlowFormController test class
 * @author            : daniel@hyphen8.com
 * @last modified on  : 05-09-2025
 * @last modified by  : daniel@hyphen8.com
**/
@isTest
public class H8FlowFormControllerTest {
    
    /**
    * @description          test missing form
    **/
    @isTest 
    static void getNoFormPresent(){
        String jsonResponse = H8FlowFormController.getForm('DUMMY FORM', new List<String>());
        Map<String, Object> jsonObjects = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        Assert.isFalse((Boolean)jsonObjects.get('success'), 'we expect this to be false');
    }

    /**
    * @description          testing a form with no child records
    **/
    @isTest 
    static void getFormPresent(){

        List<H8_Flow_Form_Section__mdt> childList = (List<H8_Flow_Form_Section__mdt>)new MockMetaManager('H8_Flow_Form_Section__mdt')
            .addFieldValue('MasterLabel', 'FirstChild')
            .addFieldValue('DeveloperName', 'FirstChild')
            .addFieldValue('Flow_API_Name__c', 'Contact')
            .addFieldValue('Icon_Name__c', 'Email')
            .addFieldValue('Order__c', '1')
            .addFieldValue('Id', 'SampleId')
            .getListMockMetaData();

        List<H8_Flow_Form__mdt> testRecords = (List<H8_Flow_Form__mdt>)new MockMetaManager('H8_Flow_Form__mdt')    
            .addFieldValue('MasterLabel', 'TestRecord')
            .addFieldValue('DeveloperName', 'TestRecord')
            .addChildren('H8_Flow_Form_Sections__r', childList)
            .getListMockMetaData();

        H8FlowFormController.formTest = testRecords[0];
        H8FlowFormController.formSectionsTest = childList;

        String jsonResponse = H8FlowFormController.getForm('Form', new List<String>());
        Map<String, Object> jsonObjects = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        Assert.isTrue((Boolean)jsonObjects.get('success'), 'we expect this to be true');
    }

    /**
    * @description          testing a form with no child records
    **/
    @isTest 
    static void getFormPresentCustomLabel(){

        List<H8_Flow_Form_Section__mdt> childList = (List<H8_Flow_Form_Section__mdt>)new MockMetaManager('H8_Flow_Form_Section__mdt')
            .addFieldValue('MasterLabel', 'H8FFSNameTestLabel')
            .addFieldValue('DeveloperName', 'H8FFSNameTestLabel')
            .addFieldValue('Flow_API_Name__c', 'Contact')
            .addFieldValue('Icon_Name__c', 'Email')
            .addFieldValue('Order__c', '1')
            .addFieldValue('Id', 'SampleId')
            .addFieldValue('Use_Custom_Label__c', true)
            .getListMockMetaData();

        List<H8_Flow_Form__mdt> testRecords = (List<H8_Flow_Form__mdt>)new MockMetaManager('H8_Flow_Form__mdt')    
            .addFieldValue('MasterLabel', 'TestRecord')
            .addFieldValue('DeveloperName', 'TestRecord')
            .addChildren('H8_Flow_Form_Sections__r', childList)
            .getListMockMetaData();

        H8FlowFormController.formTest = testRecords[0];
        H8FlowFormController.formSectionsTest = childList;

        String jsonResponse = H8FlowFormController.getForm('Form', new List<String>());
        Map<String, Object> jsonObjects = (Map<String, Object>)JSON.deserializeUntyped(jsonResponse);
        Assert.isTrue((Boolean)jsonObjects.get('success'), 'we expect this to be true');
        List<Object> sections = (List<Object>)jsonObjects.get('sections');
        for(Object section:sections){
            Map<String, Object> sectionMap = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(section));
            String labelValue = (String)sectionMap.get('label');
            System.assertEquals(Label.get(null, 'H8FFSNameTestLabel'), labelValue, 'we expect the custom label to be used');
        }
    }
}