force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <inlineHelpText>This is the API Name for the flow that you want to render</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <inlineHelpText>Use SLDS Icons here with the format standard:opportunity</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is the order that the section should appear in</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you tick this box you can set the name of section as a custom label - you do not need to include $Label. just the Label API Name will be enough</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/H8FlowFormController.cls
/**
 * @description       : Meta driven form flow controller
 * @author            : daniel@hyphen8.com
 * @last modified on  : 17-04-2025
 * @last modified by  : daniel@hyphen8.com
**/
public with sharing class H8FlowFormController {
    
    private static H8_Flow_Form__mdt form;
    public static H8_Flow_Form__mdt formTest;
    public static List<H8_Flow_Form_Section__mdt> formSectionsTest;

    /**
    * @description          aura method to get the form section structure
    * @param                formAPIName 
    * @return               String 
    **/
    @AuraEnabled 
    public static String getForm(String formAPIName){
        try {
            getFormMeta(formAPIName);
            return generateFormSectionResponse();
        } catch (Exception e){
            return generateErrorResponse(e.getMessage());
        }
    }

    /**
    * @description          method to get the selected form and associated form sections in the correct order for processing
    * @param                formAPIName 
    **/
    private static void getFormMeta(String formAPIName){
        form = Test.isRunningTest() ? formTest : [SELECT Id, MasterLabel, DeveloperName,
                                            (SELECT Id, Flow_API_Name__c, Icon_Name__c, Order__c, MasterLabel, Use_Custom_Label__c
                                            FROM H8_Flow_Form_Sections__r
                                            ORDER BY Order__c ASC)
                                            FROM H8_Flow_Form__mdt 
                                            WHERE DeveloperName=:formAPIName 
                                            WITH SECURITY_ENFORCED
                                            LIMIT 1];
    }

    /**
    * @description          method to generate the json response for the form with form sections
    * @return               String 
    **/
    private static String generateFormSectionResponse(){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeBooleanField('success', true);
            gen.writeFieldName('sections');
            gen.writeStartArray();
            List<H8_Flow_Form_Section__mdt> formSections = Test.isRunningTest() ? formSectionsTest : form.H8_Flow_Form_Sections__r;
            for(H8_Flow_Form_Section__mdt section:formSections){
                gen.writeStartObject();
                    if(section.Use_Custom_Label__c){
                        String labelValue = Label.get(null, section.MasterLabel);
                        gen.writeStringField('label', null != labelValue ? labelValue : section.MasterLabel);
                    } else {
                        gen.writeStringField('label', section.MasterLabel);
                    }
                    gen.writeStringField('icon', section.Icon_Name__c != null ? section.Icon_Name__c : '');
                    gen.writeBooleanField('hasIcon', section.Icon_Name__c != null);
                    gen.writeStringField('flow', section.Flow_API_Name__c);
                    gen.writeBooleanField('hasValidationError', false);
                    gen.writeIdField('id', section.Id);
                gen.writeEndObject();
            }
            gen.writeEndArray();
        gen.writeEndObject();
        return gen.getAsString();
    }

    /**
    * @description          method to generate an error response
    * @param                message 
    * @return               String 
    **/
    private static String generateErrorResponse(String message){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeBooleanField('success', false);
            gen.writeStringField('message', message);
        gen.writeEndObject();
        return gen.getAsString();
    }
}