force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Requirement</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Validation_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Validation_Flow_API_Name__c</fullName>
    <label>Validation Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <inlineHelpText>This is the API Name for the flow that you want to render</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <inlineHelpText>Use SLDS Icons here with the format standard:opportunity</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is the order that the section should appear in</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you tick this box you can set the name of section as a custom label - you do not need to include $Label. just the Label API Name will be enough</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/H8_Flow_Form_Section_Validation__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to support dynamic validations within forms where you want to leave all questions as optional until the final page and then only display the fields that are missing.</description>
    <label>H8 Flow Form Section Validation</label>
    <pluralLabel>H8 Flow Form Section Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/CustomErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CustomErrorMessage__c</fullName>
    <inlineHelpText>You can populate a custom error message here, the default will not display an error other than saying this field is required but you might want to include a custom error message like - This field is required as we use this within the decision making process</inlineHelpText>
    <label>Custom Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <inlineHelpText>This is the field api name that you want to validation during this process. If you want to validate a field on a parent record you should enter LookupFieldField(__r).FieldAPIName</inlineHelpText>
    <label>FieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FlowValidationType__c.field-meta.xml
<CustomField>
    <fullName>FlowValidationType__c</fullName>
    <label>FlowValidationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/H8_Flow_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form_Section__c</fullName>
    <label>H8 Flow Form Section</label>
    <referenceTo>H8_Flow_Form_Section__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Section Validations</relationshipLabel>
    <relationshipName>H8_Flow_Form_Section_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/IsFlowValidation__c.field-meta.xml
<CustomField>
    <fullName>IsFlowValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFlowValidation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>Use this to determine the order that the validation fields are returned in. To make it easier on your self set these in increments of 10 as that saves you if you need to add a new field in the middle from having to reorder everything</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/QuestionName__c.field-meta.xml
<CustomField>
    <fullName>QuestionName__c</fullName>
    <inlineHelpText>This should be the text that you have put within the question name on the flow</inlineHelpText>
    <label>Question Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you select this option you can set the Page, Question Name as custom labels, you do not need to provide $Label. just the Label API Name</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Validation_Value__c.field-meta.xml
<CustomField>
    <fullName>Validation_Value__c</fullName>
    <inlineHelpText>Enter the expected value in here this is mainly expected to be used for booleans and number fields and not have hardcoded text values within them</inlineHelpText>
    <label>Validation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/H8FlowFormCloneDeploymentTest.cls
/**
 * @description       : H8FlowFormCloneDeployment test
 * @author            : daniel@hyphen8.com
 * @last modified on  : 26-06-2025
 * @last modified by  : daniel@hyphen8.com
**/
@isTest
public class H8FlowFormCloneDeploymentTest {

    @isTest
    static void errorMissingDataTest(){
        H8FlowFormCloneDeployment.testFormValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
        H8FlowFormCloneDeployment.testFormSections = new List<H8_Flow_Form_Section__mdt>();
        Test.startTest();
            try {
                Id asyncJobId = H8FlowFormCloneDeployment.cloneFlowForm(null,null,null);
            } catch (Exception e){
                String expectedError = 'Script-thrown exception';
                System.assertEquals(expectedError, e.getMessage(), 'we expect this value to match');
            }
        Test.stopTest();
    }
    
    @isTest
    static void noConflictOfNameTest(){
        H8FlowFormCloneDeployment.testFormValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
        H8FlowFormCloneDeployment.testFormSections = new List<H8_Flow_Form_Section__mdt>();

        List<H8_Flow_Form__mdt> testFlowForms = new List<H8_Flow_Form__mdt>();
        testFlowForms.add((H8_Flow_Form__mdt)new MockMetaManager('H8_Flow_Form__mdt')
            .addFieldValue('MasterLabel', 'TestShareObjectKeyReferece')
            .addFieldValue('DeveloperName', 'TestShareObjectKeyReferece')
            .addFieldValue('Type__c', 'Application')
            .addFieldValue('Status__c', 'ACTIVE')
            .addFieldValue('Validation_Flow_API_Name__c', 'SampleFlow')
            .getSingleMockMetaData());

        H8FlowFormCloneDeployment.testForm = testFlowForms[0];

        Test.startTest();
            Id asyncJobId = H8FlowFormCloneDeployment.cloneFlowForm('TestShareObjectKeyReferece','NewForm', 'NewForm');
            System.assertEquals(asyncJobId, UserInfo.getUserId(), 'we expect these ids to match');
        Test.stopTest();
    }

    @isTest 
    static void fullTest(){

        List<H8_Flow_Form_Section_Validation__mdt> testFlowSectionsValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
        testFlowSectionsValidations.add((H8_Flow_Form_Section_Validation__mdt)new MockMetaManager('H8_Flow_Form_Section_Validation__mdt')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('CustomErrorMessage__c', 'customErrorMessage')
            .addFieldValue('DataType__c', 'String')
            .addFieldValue('Disabled__c', false)
            .addFieldValue('FieldAPIName__c', 'FieldAPIName__c')
            .addFieldValue('FlowValidationType__c', 'flowValidationType')
            .addFieldValue('IsFlowValidation__c', false)
            .addFieldValue('Order__c', 10)
            .addFieldValue('Page__c', 'pageName')
            .addFieldValue('QuestionName__c', 'questionName')
            .addFieldValue('Use_Custom_Label__c', false)
            .addFieldValue('Validation_Value__c', 'validationValue')
            .getSingleMockMetaData());

        List<H8_Flow_Form_Section__mdt> testFlowSections = new List<H8_Flow_Form_Section__mdt>();
        testFlowSections.add((H8_Flow_Form_Section__mdt)new MockMetaManager('H8_Flow_Form_Section__mdt')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('Flow_API_Name__c', 'sampleflowname')
            .addFieldValue('Icon_Name__c', 'utility:icon')
            .addFieldValue('Order__c', 10)
            .addFieldValue('Use_Custom_Label__c', false)
            .addChildren('H8_Flow_Form_Section_Validations__r', testFlowSectionsValidations)
            .getSingleMockMetaData());

        List<H8_Flow_Form__mdt> testFlowForms = new List<H8_Flow_Form__mdt>();
        testFlowForms.add((H8_Flow_Form__mdt)new MockMetaManager('H8_Flow_Form__mdt')
            .addFieldValue('MasterLabel', 'TestShareObjectKeyReferece')
            .addFieldValue('DeveloperName', 'TestShareObjectKeyReferece')
            .addFieldValue('Type__c', 'Application')
            .addFieldValue('Status__c', 'ACTIVE')
            .addFieldValue('Validation_Flow_API_Name__c', 'SampleFlow')
            .addChildren('H8_Flow_Form_Sections__r', testFlowSections)
            .getSingleMockMetaData());
        
        List<H8_Flow_Form_Section_Validation__mdt> testFlowSectionsValidationsExisting = new List<H8_Flow_Form_Section_Validation__mdt>();
        testFlowSectionsValidationsExisting.add((H8_Flow_Form_Section_Validation__mdt)new MockMetaManager('H8_Flow_Form_Section_Validation__mdt')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('CustomErrorMessage__c', 'customErrorMessage')
            .addFieldValue('DataType__c', 'String')
            .addFieldValue('Disabled__c', false)
            .addFieldValue('FieldAPIName__c', 'FieldAPIName__c')
            .addFieldValue('FlowValidationType__c', 'flowValidationType')
            .addFieldValue('IsFlowValidation__c', false)
            .addFieldValue('Order__c', 10)
            .addFieldValue('Page__c', 'pageName')
            .addFieldValue('QuestionName__c', 'questionName')
            .addFieldValue('Use_Custom_Label__c', false)
            .addFieldValue('Validation_Value__c', 'validationValue')
            .getSingleMockMetaData());

        List<H8_Flow_Form_Section__mdt> testFlowSectionsExisting = new List<H8_Flow_Form_Section__mdt>();
        testFlowSectionsExisting.add((H8_Flow_Form_Section__mdt)new MockMetaManager('H8_Flow_Form_Section__mdt')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('Flow_API_Name__c', 'sampleflowname')
            .addFieldValue('Icon_Name__c', 'utility:icon')
            .addFieldValue('Order__c', 10)
            .addFieldValue('Use_Custom_Label__c', false)
            .addChildren('H8_Flow_Form_Section_Validations__r', testFlowSectionsValidationsExisting)
            .getSingleMockMetaData());

        List<H8_Flow_Form__mdt> testFlowFormsExisting = new List<H8_Flow_Form__mdt>();
        testFlowFormsExisting.add((H8_Flow_Form__mdt)new MockMetaManager('H8_Flow_Form__mdt')
            .addFieldValue('MasterLabel', 'TestShareObjectKeyReferece')
            .addFieldValue('DeveloperName', 'TestShareObjectKeyReferece')
            .addFieldValue('Type__c', 'Application')
            .addFieldValue('Status__c', 'ACTIVE')
            .addFieldValue('Validation_Flow_API_Name__c', 'SampleFlow')
            .addChildren('H8_Flow_Form_Sections__r', testFlowSectionsExisting)
            .getSingleMockMetaData());

        H8FlowFormCloneDeployment.testForm = testFlowForms[0];
        H8FlowFormCloneDeployment.nonUniqueMasterTestLabel = 'SampleFlow';
        H8FlowFormCloneDeployment.masterLabels.add('SampleFlow');
        H8FlowFormCloneDeployment.testFormValidations = testFlowSectionsValidationsExisting;
        H8FlowFormCloneDeployment.testFormSections = testFlowSectionsExisting;

        Test.startTest();
            Id asyncJobId = H8FlowFormCloneDeployment.cloneFlowForm('TestShareObjectKeyReferece','NewForm', 'NewForm');
            System.assertEquals(asyncJobId, UserInfo.getUserId(), 'we expect these ids to match');
        Test.stopTest();
    }

    @isTest 
    static void fullTestNoDuplicates(){

        List<H8_Flow_Form_Section_Validation__mdt> testFlowSectionsValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
        testFlowSectionsValidations.add((H8_Flow_Form_Section_Validation__mdt)new MockMetaManager('H8_Flow_Form_Section_Validation__mdt')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('MasterLabel', 'childValidation')
            .addFieldValue('CustomErrorMessage__c', 'customErrorMessage')
            .addFieldValue('DataType__c', 'String')
            .addFieldValue('Disabled__c', false)
            .addFieldValue('FieldAPIName__c', 'FieldAPIName__c')
            .addFieldValue('FlowValidationType__c', 'flowValidationType')
            .addFieldValue('IsFlowValidation__c', false)
            .addFieldValue('Order__c', 10)
            .addFieldValue('Page__c', 'pageName')
            .addFieldValue('QuestionName__c', 'questionName')
            .addFieldValue('Use_Custom_Label__c', false)
            .addFieldValue('Validation_Value__c', 'validationValue')
            .getSingleMockMetaData());

        List<H8_Flow_Form_Section__mdt> testFlowSections = new List<H8_Flow_Form_Section__mdt>();
        testFlowSections.add((H8_Flow_Form_Section__mdt)new MockMetaManager('H8_Flow_Form_Section__mdt')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('MasterLabel', 'childSectionchildSectionchildSection')
            .addFieldValue('Flow_API_Name__c', 'sampleflowname')
            .addFieldValue('Icon_Name__c', 'utility:icon')
            .addFieldValue('Order__c', 10)
            .addFieldValue('Use_Custom_Label__c', false)
            .addChildren('H8_Flow_Form_Section_Validations__r', testFlowSectionsValidations)
            .getSingleMockMetaData());

        List<H8_Flow_Form__mdt> testFlowForms = new List<H8_Flow_Form__mdt>();
        testFlowForms.add((H8_Flow_Form__mdt)new MockMetaManager('H8_Flow_Form__mdt')
            .addFieldValue('MasterLabel', 'TestShareObjectKeyReferece')
            .addFieldValue('DeveloperName', 'TestShareObjectKeyReferece')
            .addFieldValue('Type__c', 'Application')
            .addFieldValue('Status__c', 'ACTIVE')
            .addFieldValue('Validation_Flow_API_Name__c', 'SampleFlow')
            .addChildren('H8_Flow_Form_Sections__r', testFlowSections)
            .getSingleMockMetaData());

        H8FlowFormCloneDeployment.testForm = testFlowForms[0];
        
        Test.startTest();
            Id asyncJobId = H8FlowFormCloneDeployment.cloneFlowForm('TestShareObjectKeyReferece','NewForm', 'NewForm');
            System.assertEquals(asyncJobId, UserInfo.getUserId(), 'we expect these ids to match');
        Test.stopTest();
    }
}