force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Requirement</fullName>
            </value>
            <value>
                <fullName>Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Validation_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Validation_Flow_API_Name__c</fullName>
    <label>Validation Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Flow_API_Name__c</fullName>
    <inlineHelpText>This is the API Name for the flow that you want to render</inlineHelpText>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Icon_Name__c.field-meta.xml
<CustomField>
    <fullName>Icon_Name__c</fullName>
    <inlineHelpText>Use SLDS Icons here with the format standard:opportunity</inlineHelpText>
    <label>Icon Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is the order that the section should appear in</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you tick this box you can set the name of section as a custom label - you do not need to include $Label. just the Label API Name will be enough</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/H8_Flow_Form_Section_Validation__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to support dynamic validations within forms where you want to leave all questions as optional until the final page and then only display the fields that are missing.</description>
    <label>H8 Flow Form Section Validation</label>
    <pluralLabel>H8 Flow Form Section Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/CustomErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CustomErrorMessage__c</fullName>
    <inlineHelpText>You can populate a custom error message here, the default will not display an error other than saying this field is required but you might want to include a custom error message like - This field is required as we use this within the decision making process</inlineHelpText>
    <label>Custom Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <inlineHelpText>This is the field api name that you want to validation during this process. If you want to validate a field on a parent record you should enter LookupFieldField(__r).FieldAPIName</inlineHelpText>
    <label>FieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FlowValidationType__c.field-meta.xml
<CustomField>
    <fullName>FlowValidationType__c</fullName>
    <label>FlowValidationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/H8_Flow_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form_Section__c</fullName>
    <label>H8 Flow Form Section</label>
    <referenceTo>H8_Flow_Form_Section__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Section Validations</relationshipLabel>
    <relationshipName>H8_Flow_Form_Section_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/IsFlowValidation__c.field-meta.xml
<CustomField>
    <fullName>IsFlowValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFlowValidation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>Use this to determine the order that the validation fields are returned in. To make it easier on your self set these in increments of 10 as that saves you if you need to add a new field in the middle from having to reorder everything</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/QuestionName__c.field-meta.xml
<CustomField>
    <fullName>QuestionName__c</fullName>
    <inlineHelpText>This should be the text that you have put within the question name on the flow</inlineHelpText>
    <label>Question Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you select this option you can set the Page, Question Name as custom labels, you do not need to provide $Label. just the Label API Name</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Validation_Value__c.field-meta.xml
<CustomField>
    <fullName>Validation_Value__c</fullName>
    <inlineHelpText>Enter the expected value in here this is mainly expected to be used for booleans and number fields and not have hardcoded text values within them</inlineHelpText>
    <label>Validation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/H8FlowFormCloneDeployment.cls
/**
 * @description       : this class performs the actual clone and deployment of the form clone
 * @author            : daniel@hyphen8.com
 * @last modified on  : 25-06-2025
 * @last modified by  : daniel@hyphen8.com
**/
public with sharing class H8FlowFormCloneDeployment {

    public static Set<String> masterLabels = new Set<String>();
    public static String nonUniqueMasterTestLabel;
    public static List<H8_Flow_Form_Section_Validation__mdt> testFormValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
    public static List<H8_Flow_Form_Section__mdt> testFormSections = new List<H8_Flow_Form_Section__mdt>();
    public static H8_Flow_Form__mdt testForm;
    
    /**
    * @description          method that supports the clone of metadata and their child / grandchild records
    * @param                sourceDeveloperName 
    * @param                newMasterLabel 
    * @param                newDeveloperName 
    **/
    @AuraEnabled
    public static void cloneFlowForm(String sourceDeveloperName, String newMasterLabel, String newDeveloperName) {
        if (String.isBlank(sourceDeveloperName) || String.isBlank(newMasterLabel) || String.isBlank(newDeveloperName)) {
            throw new AuraHandledException('All inputs are required to clone the form.');
        }
        getMasterLabels();

        H8_Flow_Form__mdt sourceForm = !Test.isRunningTest() ?[
            SELECT Id, DeveloperName, MasterLabel, Type__c, Status__c, Validation_Flow_API_Name__c,
                (SELECT DeveloperName, MasterLabel, Flow_API_Name__c, Icon_Name__c, Order__c, Use_Custom_Label__c, H8_Flow_Form__c,
                    (SELECT DeveloperName, MasterLabel, CustomErrorMessage__c, DataType__c, Disabled__c, FieldAPIName__c,
                            FlowValidationType__c, IsFlowValidation__c, Order__c, Page__c, QuestionName__c, Use_Custom_Label__c, Validation_Value__c
                        FROM H8_Flow_Form_Section_Validations__r)
                    FROM H8_Flow_Form_Sections__r)
            FROM H8_Flow_Form__mdt
            WHERE DeveloperName = :sourceDeveloperName
            LIMIT 1
        ] : testForm;

        Metadata.CustomMetadata newMetadata = new Metadata.CustomMetadata();
        newMetadata.fullName = 'H8_Flow_Form__mdt.' + newDeveloperName;
        newMetadata.label = newMasterLabel;

        newMetadata.values = new List<Metadata.CustomMetadataValue>{
            buildCMDTValue('Type__c', sourceForm.Type__c, 'String'),
            buildCMDTValue('Status__c', sourceForm.Status__c, 'String'),
            buildCMDTValue('Validation_Flow_API_Name__c', sourceForm.Validation_Flow_API_Name__c, 'String')
        };

        Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
        mdContainer.addMetadata(newMetadata);

        for (H8_Flow_Form_Section__mdt section : sourceForm.H8_Flow_Form_Sections__r) {
            Metadata.CustomMetadata newSection = new Metadata.CustomMetadata();
            String uniqueDevName = getUniqueName(newDeveloperName, section.DeveloperName);
            if(masterLabels.contains(uniqueDevName)){
                uniqueDevName = regenerateUnique(newDeveloperName, section.DeveloperName);
            } else {
                masterLabels.add(uniqueDevName);
            }
            newSection.fullName = 'H8_Flow_Form_Section__mdt.' + uniqueDevName;
            newSection.label = section.MasterLabel;

            newSection.values = new List<Metadata.CustomMetadataValue>{
                buildCMDTValue('Flow_API_Name__c', section.Flow_API_Name__c, 'String'),
                buildCMDTValue('Icon_Name__c', section.Icon_Name__c, 'String'),
                buildCMDTValue('Order__c', section.Order__c, 'String'),
                buildCMDTValue('Use_Custom_Label__c', section.Use_Custom_Label__c, 'Boolean'),
                buildCMDTValue('H8_Flow_Form__c', newDeveloperName, 'String')
            };

            mdContainer.addMetadata(newSection);
            for (H8_Flow_Form_Section_Validation__mdt validation : section.H8_Flow_Form_Section_Validations__r) {
                Metadata.CustomMetadata newValidation = new Metadata.CustomMetadata();
                String validationUniqueName = getUniqueName(uniqueDevName, validation.DeveloperName);
                if(masterLabels.contains(validationUniqueName)){
                    validationUniqueName = regenerateUnique(uniqueDevName, validation.DeveloperName);
                } else {
                    masterLabels.add(validationUniqueName);
                }
                newValidation.fullName = 'H8_Flow_Form_Section_Validation__mdt.' + validationUniqueName;
                newValidation.label = validation.MasterLabel;

                newValidation.values = new List<Metadata.CustomMetadataValue>{
                    buildCMDTValue('CustomErrorMessage__c', validation.CustomErrorMessage__c, 'String'),
                    buildCMDTValue('DataType__c', validation.DataType__c, 'String'),
                    buildCMDTValue('Disabled__c', validation.Disabled__c, 'Boolean'),
                    buildCMDTValue('FieldAPIName__c', validation.FieldAPIName__c, 'String'),
                    buildCMDTValue('FlowValidationType__c', validation.FlowValidationType__c, 'String'),
                    buildCMDTValue('IsFlowValidation__c', validation.IsFlowValidation__c, 'Boolean'),
                    buildCMDTValue('Order__c', validation.Order__c, 'String'),
                    buildCMDTValue('Page__c', validation.Page__c, 'String'),
                    buildCMDTValue('QuestionName__c', validation.QuestionName__c, 'String'),
                    buildCMDTValue('Use_Custom_Label__c', validation.Use_Custom_Label__c, 'Boolean'),
                    buildCMDTValue('Validation_Value__c', validation.Validation_Value__c, 'String'),
                    buildCMDTValue('H8_Flow_Form_Section__c', uniqueDevName, 'String')
                };

                mdContainer.addMetadata(newValidation);
            }
        }

        Id asyncJobId = !Test.isRunningTest() ? Metadata.Operations.enqueueDeployment(mdContainer, null) : UserInfo.getUserId();
    }

    /**
    * @description          helper for setting values within the metadata fields
    * @param                field 
    * @param                value 
    * @param                dataType 
    * @return               Metadata.CustomMetadataValue 
    **/
    private static Metadata.CustomMetadataValue buildCMDTValue(String field, Object value, String dataType) {
        Metadata.CustomMetadataValue val = new Metadata.CustomMetadataValue();
        val.field = field;
        if(dataType == 'String'){
            val.value = value != null ? String.valueOf(value) : '';
        } else if(dataType == 'Boolean'){
            val.value = value;
        }
        return val;
    }

    /**
    * @description          helper to ensure the developer name is unique
    * @param                newName 
    * @param                originalName 
    * @return               String 
    **/
    private static String getUniqueName(String newName, String originalName){
        String baseName = newName + originalName;
        baseName = baseName.length() > 30 ? baseName.substring(0, 30) : baseName;
        String uniqueSuffix = String.valueOf(Math.abs(Crypto.getRandomInteger())).substring(0, 6);
        String uniqueDevName = baseName + uniqueSuffix;
        uniqueDevName = uniqueDevName.length() > 40 ? uniqueDevName.substring(0, 40) : uniqueDevName;
        return (Test.isRunningTest() && null != nonUniqueMasterTestLabel) ? nonUniqueMasterTestLabel : uniqueDevName;
    }

    /**
    * @description          helper to ensure the developer name is unique
    * @param                newName 
    * @param                uniqueDevName 
    * @return               String 
    **/
    private static String regenerateUnique(String newName, String uniqueDevName){
        String uniqueName;
        for(Integer i=0;i<20;i++){
            uniqueName = getUniqueName(newName, uniqueDevName);
            if(!masterLabels.contains(uniqueName)){
                masterLabels.add(uniqueName);
                break;
            }
        }
        return uniqueName;
    }

    /**
    * @description          method to pull in and store all unique names currently within the system
    **/
    private static void getMasterLabels(){
        List<H8_Flow_Form_Section__mdt> formSections = !Test.isRunningTest() ? [SELECT MasterLabel, DeveloperName FROM H8_Flow_Form_Section__mdt] : testFormSections;
        System.debug('formSections > ' + formSections);
        for(H8_Flow_Form_Section__mdt section:formSections){
            masterLabels.add(section.DeveloperName);
        }
        List<H8_Flow_Form_Section_Validation__mdt> formValidations = !Test.isRunningTest() ? [SELECT MasterLabel, DeveloperName FROM H8_Flow_Form_Section_Validation__mdt] : testFormValidations;
        System.debug('formValidations > ' + formValidations);
        for(H8_Flow_Form_Section_Validation__mdt validation:formValidations){
            masterLabels.add(validation.DeveloperName);
        }
    }
}