force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Validation_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Validation_Flow_API_Name__c</fullName>
    <label>Validation Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/H8_Flow_Form_Section_Validation__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to support dynamic validations within forms where you want to leave all questions as optional until the final page and then only display the fields that are missing.</description>
    <label>H8 Flow Form Section Validation</label>
    <pluralLabel>H8 Flow Form Section Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <inlineHelpText>This is the field api name that you want to validation during this process. If you want to validate a field on a parent record you should enter LookupFieldField(__r).FieldAPIName</inlineHelpText>
    <label>FieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FlowValidationType__c.field-meta.xml
<CustomField>
    <fullName>FlowValidationType__c</fullName>
    <label>FlowValidationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/H8_Flow_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form_Section__c</fullName>
    <label>H8 Flow Form Section</label>
    <referenceTo>H8_Flow_Form_Section__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Section Validations</relationshipLabel>
    <relationshipName>H8_Flow_Form_Section_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/IsFlowValidation__c.field-meta.xml
<CustomField>
    <fullName>IsFlowValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFlowValidation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/QuestionName__c.field-meta.xml
<CustomField>
    <fullName>QuestionName__c</fullName>
    <inlineHelpText>This should be the text that you have put within the question name on the flow</inlineHelpText>
    <label>Question Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Validation_Value__c.field-meta.xml
<CustomField>
    <fullName>Validation_Value__c</fullName>
    <inlineHelpText>Enter the expected value in here this is mainly expected to be used for booleans and number fields and not have hardcoded text values within them</inlineHelpText>
    <label>Validation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/H8FlowFormPageValidation.cls
/**
 * @description       : Apex controller for display page level validation errors within a flow
 * @author            : daniel@hyphen8.com
 * @last modified on  : 10-09-2025
 * @last modified by  : daniel@hyphen8.com
**/
public with sharing class H8FlowFormPageValidation {

    private static H8_Flow_Form__mdt formDetails;
    private static Set<String> validationFields = new Set<String>();
    private static SObject currentRecord;
    private static List<H8_Flow_Form_Section_Validation__mdt> pageValidations = new List<H8_Flow_Form_Section_Validation__mdt>();
    private static Map<String, Object> validationValue = new Map<String, Object>();
    private static List<String> currentErrors = new List<String>();
    private static Map<String, List<String>> flowValidations = new Map<String, List<String>>();
    private static Boolean hasActiveFlowValidations = false;
    
    
    /**
    * @description              aura method to validate an individual page and display the errors
    * @param                    recordId 
    * @param                    formName 
    * @param                    parentObjectAPIName 
    * @param                    pageName 
    * @return                   String 
    **/
    @AuraEnabled 
    public static String validatePage(String recordId, String formName, String parentObjectAPIName, String pageName){
        try {
            formDetails = H8FlowFormValidationHelper.getSpecificPageForm(formName, pageName);
            getValidationFields();
            currentRecord = H8FlowFormValidationHelper.getProcessingRecord(recordId, parentObjectAPIName, validationFields);
            if(hasActiveFlowValidations) {
                flowValidations = H8FlowFormValidationHelper.getFlowValidations(formDetails.Validation_Flow_API_Name__c, formDetails.DeveloperName, null, pageName, recordId, new List<String>());     
            }
            validateCurrentRecord();
            return H8FlowFormResponseGenerator.generateFormPageResponse(true, '', currentErrors);
        } catch (Exception e){
            return H8FlowFormResponseGenerator.generateFormPageResponse(false, e.getLineNumber() + ': ' + e.toString(), currentErrors);
        }
    }

    /**
    * @description          private method to store the validation fields and validation values where provided
    **/
    private static void getValidationFields(){
        for(H8_Flow_Form_Section__mdt formSection:formDetails.H8_Flow_Form_Sections__r){
            for(H8_Flow_Form_Section_Validation__mdt formSectionValidation:formSection.H8_Flow_Form_Section_Validations__r){
                if(!formSectionValidation.IsFlowValidation__c) {
                    validationFields.add(formSectionValidation.FieldAPIName__c);
                    storeValidationValue(formSectionValidation);
                } else {
                    hasActiveFlowValidations = true;
                }
                pageValidations.add(formSectionValidation);
            }
        }
    }

    /**
    * @description      private method to store validation values
    * @param            pageValidation 
    **/
    private static void storeValidationValue(H8_Flow_Form_Section_Validation__mdt pageValidation){
        if(null != pageValidation.Validation_Value__c){
            if(pageValidation.DataType__c == 'Boolean'){
                validationValue.put(pageValidation.FieldAPIName__c, Boolean.valueOf(pageValidation.Validation_Value__c));
            } else if(pageValidation.DataType__c == 'String'){
                validationValue.put(pageValidation.FieldAPIName__c, pageValidation.Validation_Value__c);
            } else if(pageValidation.DataType__c == 'Integer'){
                validationValue.put(pageValidation.FieldAPIName__c, Integer.valueOf(pageValidation.Validation_Value__c));
            } else if(pageValidation.DataType__c == 'Decimal'){
                validationValue.put(pageValidation.FieldAPIName__c, Decimal.valueOf(pageValidation.Validation_Value__c));
            } else {
                validationValue.put(pageValidation.FieldAPIName__c, pageValidation.Validation_Value__c);
            }
        }
    }

    /**
    * @description          private method to validate the record against the validation configuration
    **/
    private static void validateCurrentRecord(){
        for(H8_Flow_Form_Section_Validation__mdt validation:pageValidations){
            if(validation.IsFlowValidation__c) {
                handleFlowValidationErrors(validation);              
            } else {
                handleCustomValidationErrors(validation);
            }
        } 
    }

    private static void handleFlowValidationErrors(H8_Flow_Form_Section_Validation__mdt validation){
        List<String> validationMessages = flowValidations.get(validation.FlowValidationType__c);
        if(validationMessages != null && validationMessages.size()>0) {
            for(String validationMessage:validationMessages) {
                currentErrors.add(validationMessage);
            }
        }
    }

    private static void handleCustomValidationErrors(H8_Flow_Form_Section_Validation__mdt validation){
        Object fieldValue = H8FlowFormValidationHelper.getFieldValue(currentRecord, validation.FieldAPIName__c);
        Object expectedValue = validationValue.containsKey(validation.FieldAPIName__c) ? validationValue.get(validation.FieldAPIName__c) : null;
        if(null == fieldValue || (null != expectedValue && expectedValue != fieldValue)){
            currentErrors.add(validation.QuestionName__c);
        }
    }
}