force-app/main/default/objects/H8_Flow_Form__mdt/H8_Flow_Form__mdt.object-meta.xml
<CustomObject>
    <description>Metadata used to control tabs and determine the order of flows</description>
    <label>H8 Flow Form</label>
    <pluralLabel>H8 Flow Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form__mdt/fields/Validation_Flow_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Validation_Flow_API_Name__c</fullName>
    <label>Validation Flow API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/H8_Flow_Form_Section__mdt.object-meta.xml
<CustomObject>
    <description>This is used to determine which flow is rendered, the name of the section determine and icon for the section and the order</description>
    <label>H8 Flow Form Section</label>
    <pluralLabel>H8 Flow Form Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/H8_Flow_Form__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form__c</fullName>
    <inlineHelpText>This is the flow form that the section is linked to</inlineHelpText>
    <label>H8 Flow Form</label>
    <referenceTo>H8_Flow_Form__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Sections</relationshipLabel>
    <relationshipName>H8_Flow_Form_Sections</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>This is the order that the section should appear in</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you tick this box you can set the name of section as a custom label - you do not need to include $Label. just the Label API Name will be enough</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/H8_Flow_Form_Section_Validation__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to support dynamic validations within forms where you want to leave all questions as optional until the final page and then only display the fields that are missing.</description>
    <label>H8 Flow Form Section Validation</label>
    <pluralLabel>H8 Flow Form Section Validations</pluralLabel>
</CustomObject>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/CustomErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CustomErrorMessage__c</fullName>
    <inlineHelpText>You can populate a custom error message here, the default will not display an error other than saying this field is required but you might want to include a custom error message like - This field is required as we use this within the decision making process</inlineHelpText>
    <label>Custom Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Disabled__c.field-meta.xml
<CustomField>
    <fullName>Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <inlineHelpText>This is the field api name that you want to validation during this process. If you want to validate a field on a parent record you should enter LookupFieldField(__r).FieldAPIName</inlineHelpText>
    <label>FieldAPIName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/FlowValidationType__c.field-meta.xml
<CustomField>
    <fullName>FlowValidationType__c</fullName>
    <label>FlowValidationType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/H8_Flow_Form_Section__c.field-meta.xml
<CustomField>
    <fullName>H8_Flow_Form_Section__c</fullName>
    <label>H8 Flow Form Section</label>
    <referenceTo>H8_Flow_Form_Section__mdt</referenceTo>
    <relationshipLabel>H8 Flow Form Section Validations</relationshipLabel>
    <relationshipName>H8_Flow_Form_Section_Validations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/IsFlowValidation__c.field-meta.xml
<CustomField>
    <fullName>IsFlowValidation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFlowValidation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>10</defaultValue>
    <inlineHelpText>Use this to determine the order that the validation fields are returned in. To make it easier on your self set these in increments of 10 as that saves you if you need to add a new field in the middle from having to reorder everything</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Page__c.field-meta.xml
<CustomField>
    <fullName>Page__c</fullName>
    <label>Page</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/QuestionName__c.field-meta.xml
<CustomField>
    <fullName>QuestionName__c</fullName>
    <inlineHelpText>This should be the text that you have put within the question name on the flow</inlineHelpText>
    <label>Question Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Use_Custom_Label__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_Label__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When you select this option you can set the Page, Question Name as custom labels, you do not need to provide $Label. just the Label API Name</inlineHelpText>
    <label>Use Custom Label</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/H8_Flow_Form_Section_Validation__mdt/fields/Validation_Value__c.field-meta.xml
<CustomField>
    <fullName>Validation_Value__c</fullName>
    <inlineHelpText>Enter the expected value in here this is mainly expected to be used for booleans and number fields and not have hardcoded text values within them</inlineHelpText>
    <label>Validation Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/H8FlowFormValidation.cls
/**
 * @description       : master form flow validation class for validating an entire form submission looking for errors
 * @author            : daniel@hyphen8.com
 * @last modified on  : 07-10-2025
 * @last modified by  : daniel@hyphen8.com
**/
public with sharing class H8FlowFormValidation {
    
    private static H8_Flow_Form__mdt formDetails;
    private static Set<String> validationFields = new Set<String>();
    private static SObject currentRecord;
    private static Map<String, Map<String, List<H8_Flow_Form_Section_Validation__mdt>>> mapOfValidations = new Map<String, Map<String, List<H8_Flow_Form_Section_Validation__mdt>>>();
    private static Map<String, Map<String, List<String>>> validationErrors = new Map<String, Map<String, List<String>>>();
    private static Map<String, Object> validationValue = new Map<String, Object>();
    private static Map<String, List<String>> flowValidations = new Map<String, List<String>>();
    private static Boolean hasActiveFlowValidations = false;
    

    /**
    * @description          Aura Method to perform validations on flow forms
    * @param                recordId 
    * @param                primaryObjectAPIName 
    * @param                formAPIName 
    * @return               String 
    **/
    @AuraEnabled
    public static String validateCompleteForm(String recordId, String primaryObjectAPIName, String formAPIName, List<String> sectionsToNotDisplay){
        try {
            formDetails = H8FlowFormValidationHelper.getCompleteForm(formAPIName, sectionsToNotDisplay);
            getValidationFields();
            currentRecord = H8FlowFormValidationHelper.getProcessingRecord(recordId, primaryObjectAPIName, validationFields);
            if(hasActiveFlowValidations) {
                flowValidations = H8FlowFormValidationHelper.getFlowValidations(formDetails.Validation_Flow_API_Name__c, formDetails.DeveloperName, null, null, recordId, sectionsToNotDisplay);             
            }
            validateCurrentRecord();
            return H8FlowFormResponseGenerator.generateFormValidationResponse(true, '', validationErrors, formDetails);
        } catch (Exception e) {
            return H8FlowFormResponseGenerator.generateFormValidationResponse(false, e.getLineNumber() + ': ' + e.toString(), validationErrors, null);
        }
    }

    /**
    * @description          private method to store the validation fields and validation values where provided
    **/
    private static void getValidationFields(){
        List<H8_Flow_Form_Section_Validation__mdt> allSectionValidations = [SELECT H8_Flow_Form_Section__c, MasterLabel, Use_Custom_Label__c, CustomErrorMessage__c, 
                                                                                    Order__c, FieldAPIName__c, QuestionName__c, Validation_Value__c, DataType__c, Page__c, 
                                                                                    IsFlowValidation__c, FlowValidationType__c 
                                                                                    FROM H8_Flow_Form_Section_Validation__mdt 
                                                                                    WHERE Disabled__c=false 
                                                                                    AND H8_Flow_Form_Section__c In:formDetails.H8_Flow_Form_Sections__r 
                                                                                    WITH SECURITY_ENFORCED
                                                                                    ORDER BY Order__c ASC NULLS LAST];
        SObjectIndex validationsBySection = new SObjectIndex('H8_Flow_Form_Section__c').putAll(allSectionValidations);

        for(H8_Flow_Form_Section__mdt formSection:formDetails.H8_Flow_Form_Sections__r){
            List<H8_Flow_Form_Section_Validation__mdt> formSectionValidations = Test.isRunningTest() ? formSection.H8_Flow_Form_Section_Validations__r : (List<H8_Flow_Form_Section_Validation__mdt>)validationsBySection.getAll(formSection.Id);
            for(H8_Flow_Form_Section_Validation__mdt formSectionValidation:formSectionValidations){
                processFormSectionsValidationRecords(formSection, formSectionValidation);
            }
        }
    }

    private static void processFormSectionsValidationRecords(H8_Flow_Form_Section__mdt formSection, H8_Flow_Form_Section_Validation__mdt formSectionValidation){
        if(!formSectionValidation.IsFlowValidation__c) {                
            validationFields.add(formSectionValidation.FieldAPIName__c);
            storeValidationValue(formSectionValidation);
        } else {
            hasActiveFlowValidations = true;
        }
        String pageName = null != formSectionValidation.Page__c ? formSectionValidation.Page__c : 'NOPAGESCONFIGURED';
        Map<String, List<H8_Flow_Form_Section_Validation__mdt>> validationsPages = mapOfValidations.containsKey(formSection.MasterLabel) ?
                                                                        mapOfValidations.get(formSection.MasterLabel) :
                                                                        new Map<String, List<H8_Flow_Form_Section_Validation__mdt>>();
        List<H8_Flow_Form_Section_Validation__mdt> validationRecords = validationsPages.containsKey(pageName) ?
                                                                        validationsPages.get(pageName) :
                                                                        new List<H8_Flow_Form_Section_Validation__mdt>();
        validationRecords.add(formSectionValidation);
        validationsPages.put(pageName, validationRecords);
        mapOfValidations.put(formSection.MasterLabel, validationsPages);
    }

    /**
    * @description      private method to store validation values
    * @param            sectionValidation 
    **/
    private static void storeValidationValue(H8_Flow_Form_Section_Validation__mdt sectionValidation){
        if(null != sectionValidation.Validation_Value__c){
            if(sectionValidation.DataType__c == 'Boolean'){
                validationValue.put(sectionValidation.FieldAPIName__c, Boolean.valueOf(sectionValidation.Validation_Value__c));
            } else if(sectionValidation.DataType__c == 'String'){
                validationValue.put(sectionValidation.FieldAPIName__c, sectionValidation.Validation_Value__c);
            } else if(sectionValidation.DataType__c == 'Integer'){
                validationValue.put(sectionValidation.FieldAPIName__c, Integer.valueOf(sectionValidation.Validation_Value__c));
            } else if(sectionValidation.DataType__c == 'Decimal'){
                validationValue.put(sectionValidation.FieldAPIName__c, Decimal.valueOf(sectionValidation.Validation_Value__c));
            } else {
                validationValue.put(sectionValidation.FieldAPIName__c, sectionValidation.Validation_Value__c);
            }
        }
    }

    /**
    * @description          private method to validate the record against the validation configuration
    **/
    private static void validateCurrentRecord(){
        for(String sectionName:mapOfValidations.keySet()){
            Map<String, List<H8_Flow_Form_Section_Validation__mdt>> pageValidations = mapOfValidations.get(sectionName);
            for(String pageName:pageValidations.keySet()){
                List<H8_Flow_Form_Section_Validation__mdt> validations = pageValidations.get(pageName);
                generateErrorFromSection(validations, sectionName);
            }
        }
    }

    private static void generateErrorFromSection(List<H8_Flow_Form_Section_Validation__mdt> validations, String sectionName){
        for(H8_Flow_Form_Section_Validation__mdt validation:validations){
            if(validation.IsFlowValidation__c) {
                handleFlowValidationErrors(sectionName, validations, validation);              
            } else {
                handleCustomValidationErrors(sectionName, validation);
            }
        } 
    }

    private static void handleFlowValidationErrors(String sectionName, List<H8_Flow_Form_Section_Validation__mdt> validations, H8_Flow_Form_Section_Validation__mdt validation){
        List<String> validationMessages = flowValidations.get(validation.FlowValidationType__c);
        if(validationMessages != null && validationMessages.size()>0) {
            for(String validationMessage:validationMessages) {
                generateError(sectionName, validation, validationMessage);
            }
        }
    }

    private static void handleCustomValidationErrors(String sectionName, H8_Flow_Form_Section_Validation__mdt validation){
        Object fieldValue = H8FlowFormValidationHelper.getFieldValue(currentRecord, validation.FieldAPIName__c);
        Object expectedValue = validationValue.containsKey(validation.FieldAPIName__c) ? validationValue.get(validation.FieldAPIName__c) : null;
        if(null == fieldValue || (null != expectedValue && expectedValue != fieldValue)){
            if(validation.Use_Custom_Label__c){
                String labelValue = Label.get(null, validation.QuestionName__c);
                generateError(sectionName, validation, null != labelValue ? labelValue : validation.QuestionName__c);
            } else {
                generateError(sectionName, validation, validation.QuestionName__c);
            }
        }
    }

    private static void generateError(String sectionName, H8_Flow_Form_Section_Validation__mdt validation, String errorMessage){
        String pageName = null != validation.Page__c ? validation.Page__c : 'NOPAGESCONFIGURED';
        Map<String, List<String>> pageErrors = validationErrors.containsKey(sectionName) ? validationErrors.get(sectionName) : new Map<String, List<String>>();
        List<String> currentErrors = pageErrors.containsKey(pageName) ? pageErrors.get(pageName) : new List<String>();
        currentErrors.add(errorMessage);
        pageErrors.put(pageName, currentErrors);
        validationErrors.put(sectionName, pageErrors);
    }
}